name: nanourls
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+7

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_tracking_transparency: ^2.0.4
  cupertino_icons: ^1.0.8
  device_info_plus: ^13.1.0
  firebase_analytics: ^12.4.3
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^11.0.0
  google_mobile_ads: ^9.0.0
  http: ^1.2.0
  package_info_plus: ^10.1.0
  path_provider: ^2.1.5
  pointycastle: ^4.0.0
  purchases_flutter: ^10.3.0
  share_plus: ^13.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.3.2


dev_dependencies:
  firebase_core_platform_interface: ^7.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/logo.svg
    - assets/svg/black_logo.svg

  fonts:
    - family: SplineSans
      fonts:
        - asset: assets/fonts/SplineSans-Light.ttf
          weight: 300
        - asset: assets/fonts/SplineSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/SplineSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/SplineSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SplineSans-Bold.ttf
          weight: 700

